/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author animesh
 */
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
public class EmailSystem extends javax.swing.JFrame {

    /**
     * Creates new form EmailSystem
     */
    int go = 0, point = 0;
    Timer timer;
    public String max_time;
    public ArrayList<String>available = new ArrayList<>();
    public ArrayList<String>occupied = new ArrayList<>();
    public ArrayList<Registration>data = new ArrayList<>();
    public EmailSystem() {
        initComponents();
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(100,100,84));
    }
    
    public EmailSystem(ArrayList<String> a, ArrayList<String> b, String str, ArrayList<Registration>c) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100,100,84));
        for(String s:a)
            available.add(s);
        for(String s:b)
            occupied.add(s);
        for(Registration s:c)
            data.add(s);
        this.max_time = str;
        String temp="";
        for(int i = 0;i < str.length();i++){
           char x = str.charAt(i);
           if(x==':')
           {
               go=Integer.parseInt(temp)*60;
               temp="";
           }
           else
               temp+=x;
        }
         go+=Integer.parseInt(temp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Successful!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(62, 255, 239));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 218, 123, 71));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 237, 202));
        jLabel1.setText("TIMER STARTED!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 124, 269, 54));

        l1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 0));
        l1.setText("Registered Successfully!!");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 49, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 30, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timer = new Timer(1000, new ActionListener(){
         public void actionPerformed(ActionEvent e){
             --go;
             if(go == 0)
             {
                 timer.stop();
                 dispose();
                 final String username = "memberdummyid@gmail.com";
                 final String password = "aarpit1010";
 
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
 
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });
 
        try {
            String y=data.get(data.size()-1).getemail_id();
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("memberdummyid@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
            InternetAddress.parse(y));
            String X = data.get(data.size()-1).getperson_name();
            String Y = data.get(data.size()-1).getvehicle_id();
            message.setSubject("Parking time expired :");
            message.setText("Hi " + X + ",!\nYour time of parking vehicle having vehicle id "+Y+" has expired. You need to either extend your duration or withdraw your vehicle from parking. Contact Smart Parking System immediately.\nThanks!!!");
            Transport.send(message);
            dispose();
            System.out.println("Mail sent succesfully!");
 
        } catch (MessagingException f) {
            throw new RuntimeException(f);
      }
//                 JOptionPane.showMessageDialog(null,"Update or Unregister vehicle having Parking ID: "+data.get(data.size()-1).getParkingID());
                 /*JDialog.setDefaultLookAndFeelDecorated(true);
                int response = JOptionPane.showConfirmDialog(null, "Do you want to Update parking time of vehicle having Parking ID: "+data.get(data.size()-1).getParkingID()+"\n & Vehicle owner name "+data.get(data.size()-1).getperson_name()+" ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.NO_OPTION) {
                  System.out.println("No button clicked");
             } else if (response == JOptionPane.YES_OPTION) {
               System.out.println("Yes button clicked");
             } */
             }
         }   
        });
        timer.start();
        dispose();
        Display second = new Display(available, occupied, max_time, data);
        second.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
