/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author animesh
 */
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;  
import java.awt.*;  
import java.util.ArrayList;

  

public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public String vehicle_id;
    public String person_name;
    public String contact_no;
    public String email_id;
    public String parking_id;
    public ArrayList<Registration>data = new ArrayList<>();
    public ArrayList<String>available = new ArrayList<>();
    public ArrayList<String>occupied = new ArrayList<>();
    static boolean go = false;
    public String max_time;
    
    Registration() {
        initComponents();
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(100,100,84));
    }
    
    Registration(ArrayList<String> a, ArrayList<String> b, String max_time, ArrayList<Registration>c) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100,100,84));
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        jc1.setModel(model);
        for(String s:a){
            available.add(s);
           model.addElement(s);
        }
        for(String s:b)
            occupied.add(s);
        for(Registration s:c)
            data.add(s);
        this.max_time = max_time;
    }
    
    Registration(String vehicle_id,String person_name,String contact_no,String email_id,String parking_id)
    {
        getContentPane().setBackground(new java.awt.Color(100,100,84));
        this.vehicle_id = vehicle_id;
        this.person_name = person_name;
        this.contact_no = contact_no;
        this.email_id = email_id;
        this.parking_id = parking_id;
    }

    public String getParkingID(){
        return this.parking_id;
    }
    public String getperson_name(){
        return this.person_name;
    }
    public String getcontact_no(){
        return this.contact_no;
    }
    public String getvehicle_id(){
        return this.vehicle_id;
    }
    public String getemail_id(){
        return this.email_id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New Vehicle");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register  New Vehicle");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 410, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Ok-icon.png"))); // NOI18N
        jButton1.setToolTipText("Click here to register your vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 100, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Actions-application-exit-icon.png"))); // NOI18N
        jButton2.setToolTipText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 97, 70));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Reset-icon.png"))); // NOI18N
        jButton3.setToolTipText("You will redirect to display frame");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 110, 70));

        l2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 210, 31));

        l3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 213, 31));

        l4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 210, 30));

        l5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 250, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 237, 202));
        jLabel6.setText("Parking ID*:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 50));

        jc1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 460, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 237, 202));
        jLabel5.setText("Email ID*:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 50));

        t4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        t4.setToolTipText("Please Enter Your Email ID");
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 460, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 237, 202));
        jLabel4.setText("Contact Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 50));

        t3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        t3.setToolTipText("Please Enter Your Contact Number");
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 460, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 237, 202));
        jLabel3.setText("Person Name*:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, 50));

        t2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        t2.setToolTipText("Please Enter Your Name");
        t2.setName(""); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 460, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 237, 202));
        jLabel2.setText("Vehicle ID*:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 120, 50));

        t1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        t1.setToolTipText("Please Enter Vehicle ID");
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 460, 50));

        jLabel7.setText("       ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Display second = new Display(available, occupied, max_time, data);
        second.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String vehicle_id = t1.getText();
        String person_name = t2.getText();
        String contact_no = t3.getText();
        String email_id = t4.getText();
        String parking_id = jc1.getSelectedItem().toString();
        
        System.out.print(parking_id);
        boolean t =false;
        if(t3.getText()==null||t3.getText().trim().equals("")){
            l5.setText("Required textfield is empty ");
            t=true;
        }
        else
            l5.setText("");
        if(!t){
            if(contact_no.length()==10){
            try {
            Long.parseLong(contact_no);
            l5.setText("");
        } catch (NumberFormatException e) {
            //Not an integer
            t = true;
            l5.setText("Should contain only digits 0-9");
        }}
            else{
                t = true;
                l5.setText("This field needs 10 digit phone no");
            }
        }
        if(t1.getText()==null||t1.getText().trim().equals("")){
            l2.setText("Required textfield is empty ");
            t=true;
        }
        else
            l2.setText("");
        if(t2.getText()==null||t2.getText().trim().equals("")){
            l3.setText("Required textfield is empty ");
            t=true;
        }
        else
            l3.setText("");
        if(t4.getText()==null||t4.getText().trim().equals("")){
            l4.setText("Required textfield is empty ");
            t=true;
        }
        else
            l4.setText("");
        if(t==true)
            return;
        Registration obj = new Registration(vehicle_id,person_name,contact_no,email_id,parking_id);
        data.add(obj);
        int index = 0;
        go = false;
        for(String s : available){
            if(s.equals(parking_id)){
                go = true;
                break;
            }
            ++index;
        }
        if(go)
        {
            available.remove(index);
            occupied.add(parking_id);
            final String username = "memberdummyid@gmail.com";
            final String password = "aarpit1010";
 
            Properties props = new Properties();
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "587");
 
            Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });
            try {
            String y=data.get(data.size()-1).getemail_id();
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("memberdummyid@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
            InternetAddress.parse(y));
            message.setSubject("Registered successfully in Smart Parking System!!");
            String A = data.get(data.size()-1).getperson_name();
            String B = data.get(data.size()-1).getvehicle_id();
            String C = data.get(data.size()-1).getcontact_no();
            String D = data.get(data.size()-1).getParkingID();
            message.setText("Hi " + A + ",! Your vehicle having vehicle id "+B+" has being registered successfully.\nUser details are following:\nName: "+A+"\nVehicle ID: "+B+"\nContact No: "+C+"\nParking ID: "+D+"\n\nThanks for using our service.");
 
            Transport.send(message);
 
            System.out.println("Mail sent succesfully!");
            dispose();
 
        } catch (MessagingException f) {
            throw new RuntimeException(f);
      }
        }
        dispose();
        if(go)
        {
            //JOptionPane.showMessageDialog(null,"Registered Successfully!!");
            EmailSystem fourth = new EmailSystem(available, occupied, max_time, data);
            fourth.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid Parking ID asked by user.\n Enter valid Parking ID ");
            Display second = new Display(available, occupied, max_time, data);
            second.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
