/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author animesh
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    public ArrayList<Registration>data  = new ArrayList<>();
    public ArrayList<String>available = new ArrayList<>();
    public ArrayList<String>occupied = new ArrayList<>();
    public String max_time;
    public Withdraw() {
        initComponents();
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(100,100,84));
    }
    
     public Withdraw(ArrayList<String> a, ArrayList<String> b, String max_time, ArrayList<Registration>c) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100,100,84));
        for(String s:a)
            available.add(s);
        for(String s:b)
            occupied.add(s);
        for(Registration s:c)
            data.add(s);
        this.max_time = max_time;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Withdraw The Vehicle");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Withdraw the Vehicle");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 380, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Ok-icon.png"))); // NOI18N
        jButton1.setToolTipText("Withdraw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 99, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Actions-application-exit-icon.png"))); // NOI18N
        jButton2.setToolTipText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 90, 70));

        l1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 260, 40));

        l2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 270, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 237, 202));
        jLabel1.setText("Vehicle Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 60));

        t1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 260, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 237, 202));
        jLabel3.setText("Parking Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 196, 130, 60));

        t2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 260, 60));

        jLabel4.setText("      ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean t=false;
        if(t1.getText()==null||t1.getText().trim().equals("")){
            l1.setText("Required textfield is empty ");
            t=true;
        }
        else
            l1.setText("");
        if(t2.getText()==null||t2.getText().trim().equals("")){
            l2.setText("Required textfield is empty ");
            t=true;
        }
        else
            l2.setText("");
        if(t==true)
            return;
        String x,y;
        x = t1.getText();
        y = t2.getText();
        boolean f = false;
        int ind = -1;
        for(int i = 0;i < data.size();i++){
            if(data.get(i).getvehicle_id().equals(x) && data.get(i).getParkingID().equals(y)){
                f = true;
                ind = i;
                break;
            }
        }
        if(f){
            int index = 0;
            for(String s : occupied){
                if(s.equals(y)){
                break;
               }
            ++index;
            }
            occupied.remove(index);
            available.add(y);
            JOptionPane.showMessageDialog(null,"Withdrawl vehicle successfully!!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Unauthorized Access!!");
        }
        dispose();
        Display second = new Display(available, occupied, max_time, data);
        second.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Display second = new Display(available, occupied, max_time, data);
        second.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
